version: "3.10.1"

services:
    website:
        image: msyhdotfm-website:latest
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./:/app/:rw,cached
        depends_on:
            - db_migrate
        ports:
            - 8000:8000

    db_migrate:
      image: msyhdotfm-website:latest
      command: python manage.py migrate
      volumes:
          - ./:/app/:rw,cached
