# Generated by Django 4.2.6 on 2023-10-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200)),
                ('event_details', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
